version: "3.8"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    command: --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    networks:
      - mongo-network
    ports:
      - "27017:27017"

volumes:
  mongodb_data:

networks:
  mongo-network:
